{"name": "Bilgiler boş geçildiginde uyari mesaji alma kontrolü", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following failure was found in \"test_bilgiler_bos_gecildiginde_uyari_meajlari_goruntulenmesi_FAIL\" (test_kayit_ol.TestKayitOl):\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/standard/Desktop/Tobeto-Test-Team-Project/tests/test_kayit_ol.py\", line 27, in test_bilgiler_bos_gecildiginde_uyari_meajlari_goruntulenmesi_FAIL\n    self.soft_assert(self.assertTrue, beklenen_zorunlu_alan_sayisi == kayit_ol_object.zorunlu_alan_karsilastirma(), \"BEKLENILEN POPUP GORUNTULENMEDI.\")\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 729, in assertTrue\n    raise self.failureException(msg)\nAssertionError: False is not true : BEKLENILEN POPUP GORUNTULENMEDI.\n\n-+ [1/1] +-", "trace": "self = <test_kayit_ol.TestKayitOl testMethod=test_bilgiler_bos_gecildiginde_uyari_meajlari_goruntulenmesi_FAIL>\n\n    @allure.title(\"Bilgiler boş geçildiginde uyari mesaji alma kontrolü\")\n    def test_bilgiler_bos_gecildiginde_uyari_meajlari_goruntulenmesi_FAIL(self): # != SEKLİNDE YAZILDI\n        kayit_ol_object = KayitOlFonksiyonu(self.driver)\n        kayit_ol_object.bos_kayit()\n        beklenen_zorunlu_alan_sayisi = int(5)\n        self.soft_assert(self.assertTrue, beklenen_zorunlu_alan_sayisi == kayit_ol_object.zorunlu_alan_karsilastirma(), \"BEKLENILEN POPUP GORUNTULENMEDI.\")\n>       self.assert_all()\n\ntests/test_kayit_ol.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following failure was found in \"test_bilgiler_bos_gecildiginde_uyari_meajlari_goruntulenmesi_FAIL\" (test_kayit_ol.TestKayitOl):\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/standard/Desktop/Tobeto-Test-Team-Project/tests/test_kayit_ol.py\", line 27, in test_bilgiler_bos_gecildiginde_uyari_meajlari_goruntulenmesi_FAIL\nE       self.soft_assert(self.assertTrue, beklenen_zorunlu_alan_sayisi == kayit_ol_object.zorunlu_alan_karsilastirma(), \"BEKLENILEN POPUP GORUNTULENMEDI.\")\nE     File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 729, in assertTrue\nE       raise self.failureException(msg)\nE   AssertionError: False is not true : BEKLENILEN POPUP GORUNTULENMEDI.\nE   \nE   -+ [1/1] +-"}, "start": 1714736094742, "stop": 1714736126158, "uuid": "387da83a-b303-4335-8b2c-fab4b11c6748", "historyId": "24d06d9e8dc45870fa9d70c87d38a31d", "testCaseId": "24d06d9e8dc45870fa9d70c87d38a31d", "fullName": "tests.test_kayit_ol.TestKayitOl#test_bilgiler_bos_gecildiginde_uyari_meajlari_goruntulenmesi_FAIL", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_kayit_ol"}, {"name": "subSuite", "value": "TestKayitOl"}, {"name": "host", "value": "elif.local"}, {"name": "thread", "value": "6751-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_kayit_ol"}]}